### ISSUE TITLE
Use Sparkfun LSM9DS1 library

### ISSUE THREAD

**Issue by hstarmans** [arduino-libraries/Arduino_LSM9DS1#7]
The main problem with the library is that it is very limited as compared to [sparkfun LSM9DS1](https://github.com/sparkfun/SparkFun_LSM9DS1_Arduino_Library/blob/master/LICENSE.md)
This made me wonder what Arduino has been up to. Why didn't they simply clone and slightly modify this library?
You can't change the settings of LSM9DS1 with this library.
You can use this sparkfun library by passing imu.begin(0x6B, 0X1E, Wire1) to LSM9DS1. The library has options to change settings, like sampling rate etc. If you use the sparkfun library it will complain about some statements in SPI, you need to comment these out, see my other comment [here](https://github.com/arduino-libraries/Arduino_LSM9DS1/issues/2#issuecomment-588430552).

While I am at it... the whole arduino IDE was also working badly on ubuntu 18.04; had to run
```
sudo apt --purge remove modemmanager
```
See issues [here](https://community.arduboy.com/t/resolved-issues-uploading-with-ubuntu-18-10-and-arduino-1-8-9/7447/3)

**Comment by cmaglie** [comment]
hi @hstarmans 

What can I say, for our purposes it's working well, searching for `LSM9DS1` I found at least 5 libraries:

```
"Adafruit LSM9DS1 Library"
"Arduino_LSM9DS1"
"Melopero LSM9DS1"
"SmartEverything LSM9DS1"
"SparkFun LSM9DS1 IMU"
```

Sometimes diversity is a good thing, sometimes not... it's not always easy to coordinate efforts.
BTW nothing stops you from trying other libraries or pushing fixes to the existing ones and I think this is the most important thing.

> While I am at it... the whole arduino IDE was also working badly on ubuntu 18.04; had to run: sudo apt --purge remove modemmanager

It's not the IDE that is "working badly", it's `modemmanager` that tries to connect to the serial ports (because it thinks that the Arduino serial port is a modem and it tries to connect to it) that's why the IDE found the port "busy". I remember there was a long discussion in the Ubuntu/modemmanager issue tracker, I guess that latest version of modemmanager should have fixed that behaviour, but I didn't follow closely the thread really.
